//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client : User
    {
        public Client()
        {
            this.Bankcard = new HashSet<Bankcard>();
            this.Order = new HashSet<Order>();
            this.Comment = new HashSet<Comment>();
        }
    
        public string surname { get; set; }
    
        public virtual ICollection<Bankcard> Bankcard { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
