//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Cartline = new HashSet<Cartline>();
        }
    
        public long Id { get; set; }
        public System.DateTime orderDate { get; set; }
        public string orderAddress { get; set; }
        public long bankcardNumber { get; set; }
    
        public virtual ICollection<Cartline> Cartline { get; set; }
        public virtual Client Client { get; set; }
    }
}
