//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductPorperty = new HashSet<ProductProperty>();
        }

        public Product(string name, double price, DateTime creationDate, int stock, Category category)
        {
            this.name = name;
            this.price = price;
            this.creationDate = creationDate;
            this.stock = stock;
            Category = category;
        }

        public long Id { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public System.DateTime creationDate { get; set; }
        public int stock { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<ProductProperty> ProductPorperty { get; set; }
    }
}
