//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant : User
    {
        public Restaurant()
        {
            this.Product = new HashSet<Product>();
            this.Comment1 = new HashSet<Comment>();
        }
    
        public string schedule { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Comment> Comment1 { get; set; }
    }
}
